name: food_app
description: Food Application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.0.2
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  animated_splash_screen: ^1.2.0
  search_page: ^2.0.0+1
  toggle_switch: ^2.0.1
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Thin.ttf
        - asset: assets/font/Poppins-Light.ttf
          style: italic
